# image will be published to ghcr.io/<user>/<name>
name: seal-os
# description will be included in the image's metadata
description: Operating system designed for Seals.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - micro
      - hyprland
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks 

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - io.gitlab.librewolf-community
        - org.libreoffice.LibreOffice
        - com.vscodium.codium
        - org.kde.krita
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - io.github.flattool.Warehouse
        - io.missioncenter.MissionCenter
        - dev.deedles.Trayscale
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: justfiles
  #  validate: true
    include:
      - bluefin

  - type: gnome-extensions
    install:
      - Blur my Shell
      - AppIndicator and KStatusNotifierItem Support
    uninstall:
    #  - GSConnect 

  - type: gschema-overrides
    include:
      - zz1-base.gschema.override 

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

